### ISSUE TITLE
Code Enhancment

### ISSUE THREAD

**Issue by BeqaLobzhanidze** [ikverenc/space-project#10]

**Comment by BeqaLobzhanidze** [comment]
`
//* Hooks
import isUserAuthorized from '../../hooks/useAuth';

//* Routes
import { PAGES_ROUTES } from '../routes';

const ProtectedRoutes = () => {
    const userIsAuthorized = isUserAuthorized();

    return userIsAuthorized === true ? <Outlet /> : <Navigate to={PAGES_ROUTES.ROOT} />;
}

export default ProtectedRoutes;
`

**Comment by ikverenc** [comment]
Yeap, all cleaned up! 🤪

**Comment by BeqaLobzhanidze** [comment]
> Yeap, all cleaned up! 🤪

Nice !
